language: "node_js"
sudo: false
node_js:
    - "10"
before_install:
  - "npm install -g bower purescript pulp"
script:
  - "bower install"
  - "pulp build"
  # Can't "pulp test", for two reasons:
  # * Do not have mock Screeps API yet
  # * as the Test.Main.main exits with 1; it's not a test definition so much as an example of use.
